### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/XmlAdapter

### ISSUE THREAD

**Issue by ahmetgul93** [smartdec/smartcheck#13]
Hello,

I try to analyze my contract by writing 

C:\Users\asus\Desktop\SampleJavaProj>smartcheck -p AlarmClock.sol

However I got error.

Could you please help to pass this error ?

My Java version : java 11 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode) 

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/XmlAdapter
        at ru.smartdec.smartcheck.app.cli.Tool.makeDirectoryAnalysis(Tool.java:126)
        at ru.smartdec.smartcheck.app.cli.Tool.run(Tool.java:145)
        at ru.smartdec.smartcheck.app.cli.Tool.main(Tool.java:81)
        at ru.smartdec.smartcheck.app.cli.Tool.main(Tool.java:36)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.adapters.XmlAdapter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 4 more

**Comment by ahmetgul93** [comment]
Hello,

I downloaded JAVA 7. Then, it worked !

**Comment by eMarchenko** [comment]
Hello,
SmartCheck works with Java 8. You can try [these tricks](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j) for newer versions.
