### ISSUE TITLE
Java Exception Reported When Running Smartcheck

### ISSUE THREAD

**Issue by OSUPlayer** [smartdec/smartcheck#14]
Hi, I have tried to install smartcheck by using npm. It succeeded but reported exception when run smartcheck:

Exception in thread "main" java.lang.IllegalArgumentException
	at java.util.Optional.orElseThrow(Optional.java:290)
	at ru.smartdec.smartcheck.app.cli.Tool.main(Tool.java:48)
	at ru.smartdec.smartcheck.app.cli.Tool.main(Tool.java:36)

What should i do?

Environment Information:
OS: Ubuntu 18.04 LTS
JDK Version: JDK 8_u131
Node.js Version: 10.15.1 LTS

**Comment by OSUPlayer** [comment]
It is fixed when I add "-p" in command.
