### ISSUE TITLE
cannot find XmlAdapter

### ISSUE THREAD

**Issue by bguiz** [smartdec/smartcheck#22]
After running a global install:

```
$ npm install @smartdec/smartcheck -g
/Users/bguiz/.nvm/versions/node/v10.15.0/bin/smartcheck -> /Users/bguiz/.nvm/versions/node/v10.15.0/lib/node_modules/@smartdec/smartcheck/jdeploy-bundle/jdeploy.js
+ @smartdec/smartcheck@2.0.1
added 17 packages from 12 contributors in 1.592s
```

... installation succeeded, but errored immediately upon running:

```
$ smartcheck -p .
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/XmlAdapter
	at ru.smartdec.smartcheck.app.cli.Tool.makeDirectoryAnalysis(Tool.java:126)
	at ru.smartdec.smartcheck.app.cli.Tool.run(Tool.java:145)
	at ru.smartdec.smartcheck.app.cli.Tool.main(Tool.java:81)
	at ru.smartdec.smartcheck.app.cli.Tool.main(Tool.java:36)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.adapters.XmlAdapter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 4 more
```

Is there some other step involved? 

```
$ java --version
java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

^ this is the version of java that I have

**Comment by eMarchenko** [comment]
I guess it's because of java version. SmartCheck is developed and tested for java 8.

**Comment by Thanu317** [comment]
can you help to fix this issue

**Comment by eMarchenko** [comment]
I'm afraid that the only way to solve this issue is to install a supported java version.

**Comment by Thanu317** [comment]
Can you guide me how to write it in workflow for github action

**Comment by eMarchenko** [comment]
You need Java 8.
You might have to select a particular release (some subversion in 100+ range were not working properly).

Overall, SmartCheck wasn't supposed to be run on CI. I can't help you with this, unfortunately.
