### ISSUE TITLE
Installation is done, but the app shows errors when it runs from the terminal

### ISSUE THREAD

**Issue by kld4net** [smartdec/smartcheck#26]
I just installed the smrtcheck and run it from the mac terminal but it shows the following exception:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/XmlAdapter
	at ru.smartdec.smartcheck.app.cli.Tool.makeDirectoryAnalysis(Tool.java:126)
	at ru.smartdec.smartcheck.app.cli.Tool.run(Tool.java:145)
	at ru.smartdec.smartcheck.app.cli.Tool.main(Tool.java:81)
	at ru.smartdec.smartcheck.app.cli.Tool.main(Tool.java:36)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.adapters.XmlAdapter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 4 more

**Comment by sigma67** [comment]
Check your Java version. Java 8 needs to be the default JRE on your system

**Comment by kld4net** [comment]
Thank you, it is working now!
