### ISSUE TITLE
Building Using source code of SmartCheck failed

### ISSUE THREAD

**Issue by saarshah** [smartdec/smartcheck#27]
I am trying an option of Using source code of SmartCheck. I have done following steps

1. I have git clone your code
2. then in the root folder of smartcheck, i run `mvn clean package`
this gives my following error
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.380 s
[INFO] Finished at: 2020-01-06T16:28:24+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project smartcheck: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
I have following versions of :
 **java version** "11.0.5" 2019-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)

**Apache Maven** 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\apache-maven-3.6.3\bin\..
Java version: 11.0.5, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.5
Default locale: en_SG, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**When i have changed**               
```
<maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
```

then following error occurred
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-pmd-plugin:3.7:pmd (pmd) on project smartcheck: Execution pmd of goal org.apache.maven.plugins:maven-pmd-plugin:3.7:pmd failed: org.apache.maven.reporting.MavenReportException: Unsupported targetJdk value '11.0.5'. -> [Help 1] `
**UPDATED:**
when i run this on **java 1.8 and window** **8,** then following error occurred:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running ru.smartdec.smartcheck.RulesTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.257 sec <<< FA
ILURE!
patterns(ru.smartdec.smartcheck.RulesTest)  Time elapsed: 8.12 sec  <<< ERROR!
java.lang.RuntimeException: Unexpected file C:\Users\Jawad\smartcheck\target\tes
t-classes\rules\SOLIDITY_UNUSED_FUNCTION_SHOULD_BE_EXTERNAL.SOL
        at ru.smartdec.smartcheck.RulesTest.patternsActual(RulesTest.java:194)
        at ru.smartdec.smartcheck.RulesTest.patterns(RulesTest.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
Method.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
lable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
thod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMet
hod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.
java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(
ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke
(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(Provi
derFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
75)


Results :

Tests in error:
  patterns(ru.smartdec.smartcheck.RulesTest): Unexpected file C:\Users\Jawad\sma
rtcheck\target\test-classes\rules\SOLIDITY_UNUSED_FUNCTION_SHOULD_BE_EXTERNAL.SO
L

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:23 min
[INFO] Finished at: 2020-01-06T14:06:22+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
12.4:test (default-test) on project smartcheck: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Jawad\smartcheck\target\surefire-reports for th
e individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
```

**Comment by saarshah** [comment]
I have resolved this issue, there is a file `SOLIDITY_UNUSED_FUNCTION_SHOULD_BE_EXTERNAL.SO
L` , its extension is in capital which should be in small case ".sol" , then problem solved.
