### ISSUE TITLE
Problem to run this application getting output  with "Exception in thread "main" java.lang.IllegalArgumentException"

### ISSUE THREAD

**Issue by shazzySuresh** [smartdec/smartcheck#3]
Hi, i had been trying to build this application in the Intellij Idea, but my problem is after i had build everything and run , i keep on getting this error as below, and i need your help to teach me or show me what should i do to make this thing go away and get the correct output when run this system. Thank you. 

Exception in thread "main" java.lang.IllegalArgumentException
	at java.util.Optional.orElseThrow(Optional.java:290)
	at ru.smartdec.soliditycheck.app.cli.Tool.main(Tool.java:42)
	at ru.smartdec.soliditycheck.app.cli.Tool.main(Tool.java:30)

**Comment by B-doublemint** [comment]
Hello, may i ask you a question? Is the SolidityParser.java file missing from your project?

**Comment by B-doublemint** [comment]
> Hi, i had been trying to build this application in the Intellij Idea, but my problem is after i had build everything and run , i keep on getting this error as below, and i need your help to teach me or show me what should i do to make this thing go away and get the correct output when run this system. Thank you.
> 
> Exception in thread "main" java.lang.IllegalArgumentException
> at java.util.Optional.orElseThrow(Optional.java:290)
> at ru.smartdec.soliditycheck.app.cli.Tool.main(Tool.java:42)
> at ru.smartdec.soliditycheck.app.cli.Tool.main(Tool.java:30)

Hello, may i ask you a question? Is the SolidityParser.java file missing from your project?

**Comment by DiscoVan** [comment]
Hi, @shazzySuresh ! Thanks for the feedback! We have updated SmartCheck significantly. Could you please try again and say whether the problem persists?
