### ISSUE TITLE
Issue in running analysis on installation using NPM

### ISSUE THREAD

**Issue by Aniket-Engg** [smartdec/smartcheck#40]
Installation as a npm global package goes fine but while running analysis for a file like:
`smartcheck -p ./contracts/Greeter.sol`

shows error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/XmlAdapter
	at ru.smartdec.smartcheck.app.cli.Tool.makeDirectoryAnalysis(Tool.java:126)
	at ru.smartdec.smartcheck.app.cli.Tool.run(Tool.java:145)
	at ru.smartdec.smartcheck.app.cli.Tool.main(Tool.java:81)
	at ru.smartdec.smartcheck.app.cli.Tool.main(Tool.java:36)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.adapters.XmlAdapter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 4 more
```

**Comment by eMarchenko** [comment]
Hi @Aniket-Engg , what version of JDK do you use? SmartCheck works only with older java8 versions, e.g. 8u102.
You can download it from:
https://www.oracle.com/ru/java/technologies/javase/javase8-archive-downloads.html
